//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeBeerProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class CheckInOut
    {
        public int RecordId { get; set; }
        public int EmpCode { get; set; }
        public System.DateTime BeginWork { get; set; }
        public Nullable<System.DateTime> EndWork { get; set; }
        public Nullable<int> BreakCode { get; set; }
        public Nullable<System.DateTime> BeginBreak { get; set; }
        public Nullable<System.DateTime> EndBreak { get; set; }
    
        public virtual Break Break { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
